language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9

dist: xenial

cache: pip

before_install:
- npm install npm@latest -g
- sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc

install:
- pip install tox-travis

before_script:
- pip3 install -r requirements.txt
- pip3 install -r requirements-dev.txt
- pip3 install --editable .
- pip3 install -U python-dotenv

script:
- tox

after_success:
- build/testScript.sh

before_deploy:
- pip3 install bumpversion pypandoc
- sudo apt-get update
- sudo apt-get install pandoc
- nvm install 12
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github

deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    python: 3.8
    branch: main
- provider: pypi
  user: $PYPI_USER
  password: "$PYPI_PASSWORD"
  repository: https://upload.pypi.org/legacy
  skip_cleanup: true
  on:
    python: 3.8
    tags: true