language: python
python:
- 3.8
cache: pip
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .env.enc -out .env -d || true'
- npm install npm@latest -g
install:
- pip3 install tox-travis
before_script:
- pip3 install -r requirements.txt
- pip3 install -r requirements-dev.txt
- pip3 install --editable .
script:
- pip3 install -U python-dotenv
- tox
before_deploy:
- pip3 install bumpversion pypandoc
- sudo apt-get update
- sudo apt-get install pandoc
- nvm install 12
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github
deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    python: 3.8
    branch: main
- provider: pypi
  user: $PYPI_USER
  password: "$PYPI_PASSWORD"
  repository: https://upload.pypi.org/legacy
  skip_cleanup: true
  on:
    python: 3.8
    tags: true