name: CI/CD Pipeline
on: [push, pull_request, workflow_dispatch]

jobs:
  verify:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore') && !startsWith(github.ref, 'refs/tags/v')"
    strategy:
      matrix: 
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v1

      - name: setting up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install dependencies
        run: make setup

      - name: linting
        run: make lint

  test:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore') && !startsWith(github.ref, 'refs/tags/v')"
    strategy:
      matrix: 
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: setup extensions
        uses: actions/checkout@v1

      - name: setting up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: make setup

      - name: running unit tests
        run: make test-unit

      - name: running integration tests
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          FINDINGS_ENV: ${{ secrets.FINDINGS_ENV }}
          NOTIFICATIONS_ENV: ${{ secrets.NOTIFICATIONS_ENV }}
          CONFIGURATION_GOVERNANCE_ENV: ${{ secrets.CONFIGURATION_GOVERNANCE_ENV }}
          RESOURCE_GROUP_ID: ${{ secrets.RESOURCE_GROUP_ID }}
        run: build/testScript.sh

  release:
    runs-on: ubuntu-latest
    needs: [verify, test]
    if: "github.event_name == 'push' && github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'chore')"
    steps:
      - name: setup extensions
        uses: actions/checkout@v1

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: release using semantic-release
        env:
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          GIT_AUTHOR_NAME: scccomm
          GIT_AUTHOR_EMAIL: scccomm@in.ibm.com
          GIT_COMMITTER_NAME: scccomm
          GIT_COMMITTER_EMAIL: scccomm@in.ibm.com
        run: |
          sudo apt-get update
          sudo apt-get install python
          pip install --user bumpversion
          npm install @semantic-release/changelog
          npm install @semantic-release/exec
          npm install @semantic-release/git
          npm install @semantic-release/github
          npx semantic-release

  publish:
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')"
    steps:
      - name: setup extensions
        uses: actions/checkout@v1

      - name: install build module
        run: |
          python -m pip install --upgrade pip
          pip install build
      
      - name: build project
        run: python -m build

      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PASSWORD }}
          repository_url: https://upload.pypi.org/legacy/

  documentation:
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')"
    steps:
      - name: setup extensions
        uses: actions/checkout@v1

      - name: install pdoc
        run: pip install pdoc

      - name: generate pydoc
        run: |
          pip install -e .
          pdoc ibm_scc -o html
      
      - name: deploy gopages to gh-pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: html
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}